<a href="https://colab.research.google.com/github/sheCodesAI/stats/blob/main/modify_Z_score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/movie_revenues.csv")

In [4]:
df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",12/10/2009,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,54000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.youmeanddupree.com/,1819,"[{""id"": 1253, ""name"": ""roommate""}, {""id"": 2038...",en,"You, Me and Dupree",After standing in as best man for his longtime...,18.600367,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",7/14/2006,130431368,108,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Two's company. Dupree's a crowd.,"You, Me and Dupree",5.4,407

In [5]:
df.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.600000e+01,46.000000,46.000000,4.600000e+01,46.000000,46.000000,46.000000
mean,4.549239e+07,57601.782609,40.342615,1.879289e+08,110.413043,6.250000,1233.413043
std,4.529615e+07,88002.107776,64.479614,4.551144e+08,17.994538,0.694342,2093.319773
min,4.500000e+05,59.000000,0.280083,8.522060e+05,77.000000,4.700000,4.000000
25%,2.125000e+07,3156.750000,11.610217,2.866957e+07,96.250000,5.825000,251.500000
50%,3.000000e+07,12506.500000,30.140234,8.381714e+07,108.000000,6.300000,733.000000
75%,5.500000e+07,52522.500000,38.918290,1.382135e+08,121.750000,6.700000,1238.000000
max,2.370000e+08,298312.000000,418.708552,2.787965e+09,162.000000,7.500000,11800.000000

In [6]:
df.revenue.describe()

count    4.600000e+01
mean     1.879289e+08
std      4.551144e+08
min      8.522060e+05
25%      2.866957e+07
50%      8.381714e+07
75%      1.382135e+08
max      2.787965e+09
Name: revenue, dtype: float64

In [9]:
df['revenue_mln'] = df['revenue'].apply(lambda x:x/1000000)
df.revenue_mln.describe()

count      46.000000
mean      187.928898
std       455.114423
min         0.852206
25%        28.669569
50%        83.817142
75%       138.213502
max      2787.965087
Name: revenue_mln, dtype: float64

In [10]:
_, mean, std, *_ = df.revenue_mln.describe()

In [11]:
mean, std

(187.92889841304347, 455.1144234195408)

In [12]:
def get_z_score(value, mean, std) :
  return (value - mean)/std

In [16]:
df['get_z_score']= df.revenue_mln.apply(lambda x: get_z_score(x, mean, std))

In [17]:
df.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_mln,get_z_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087,5.712929
1,54000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",http://www.youmeanddupree.com/,1819,"[{""id"": 1253, ""name"": ""roommate""}, {""id"": 2038...",en,"You, Me and Dupree",After standing in as best man for his longtime...,18.600367,"[{""name"": ""Universal Pictures"", ""id"": 33}, {""n...",...,130431368,108,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Two's company. Dupree's a crowd.,"You, Me and Dupree",5.4,407,130.431368,-0.126336
2,21000000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name...",NaN,2575,"[{""id"": 246, ""name"": ""dancing""}, {""id"": 470, ""...",en,The Tailor of Panama,A British spy is banished to Panama after havi...,7.047975,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,28008462,109,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,"In a place this treacherous, what a good spy n...",The Tailor of Panama,6.2,92,28.008462,-0.351385

In [20]:
df[df.get_z_score>3]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_mln,get_z_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,2787965087,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087,5.712929

In [23]:
def get_mad(s):
  median = np.median(s)
  diff = abs(s-median)
  MAD = np.median(diff)
  return MAD

In [26]:
import numpy as np
MAD = get_mad(df.revenue_mln)
median = np.median(df.revenue_mln)
print(MAD, median)

56.399542499999995 83.8171415

In [28]:
df['mod_z_score'] = df.revenue_mln.apply(lambda x: get_z_score(x, median, MAD))

In [29]:
df[df.mod_z_score>3.5]

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,revenue_mln,get_z_score,mod_z_score
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,2787.965087,5.712929,47.946274
7,150000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.jurassicworld.com/,135397,"[{""id"": 1299, ""name"": ""monster""}, {""id"": 1718,...",en,Jurassic World,Twenty-two years after the events of Jurassic ...,418.708552,"[{""name"": ""Universal Studios"", ""id"": 13}, {""na...",...,124,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The park is open.,Jurassic World,6.5,8662,1513.528810,2.912674,25.349703
12,25000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 28, ""n...",NaN,619,"[{""id"": 1156, ""name"": ""sister sister relations...",en,The Bodyguard,A former Secret Service agent grudgingly takes...,26.576385,"[{""name"": ""Tig Productions"", ""id"": 335}, {""nam...",...,129,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Never let her out of your sight. Never let you...,The Bodyguard,6.1,661,411.006740,0.490158,5.801281
17,50000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",NaN,2898,"[{""id"": 641, ""name"": ""single parent""}, {""id"": ...",en,As Good as It Gets,"New York City. Melvin Udall, a cranky, bigoted...",37.885022,"[{""name"": ""Gracie Films"", ""id"": 18}, {""name"": ...",...,139,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,A comedy from the heart that goes for the throat.,As Good as It Gets,7.2,915,314.178011,0.277401,4.084446
36,100000000,"[{""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""...",NaN,869,"[{""id"": 690, ""name"": ""gorilla""}, {""id"": 1826, ...",en,Planet of the Apes,After a spectacular crash-landing on an unchar...,51.188633,"[{""name"": ""Twentieth Century Fox Film Corporat...",...,119,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You'll be sorry you were ever born human,Planet of the Apes,5.6,1243,362.211740,0.382943,4.936114
43,110000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 10752, ""...",http://www.300themovie.com/,53182,"[{""id"": 18712, ""name"": ""based on graphic novel...",en,300: Rise of an Empire,Based on Frank Miller's latest graphic novel X...,71.510596,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,102,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Seize your glory!,300: Rise of an Empire,6.1,2397,337.580051,0.328821,4.499379